name: Compile Kernel
on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4.2.0
        with:
          submodules: false

      - name: Install Verified AOSP Kernel Compilation Toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev libelf-dev lld llvm ccache build-essential libncurses-dev python3 git rsync liblz4-tool

      - name: Execute Verified Submodule Build Engine
        run: bash build_kernel.sh
